### ISSUE TITLE
possible bug/feature in Convolutional Coding

### ISSUE THREAD

**Issue by dchutchings** [rwnobrega/komm#1]
I'm impressed with the communications utilities implementation so far.

I have found that the message obtained with komm.ConvolutionalStreamEncoder followed by komm.ConvolutionalStreamDecoder does not match the original, as per the current Matlab Communications Toolbox implementation. The data bits have been shifted by a number of bits corresponding to the traceback_length. The documentation notes "... The output stream has a delay equal to kτ, where k is the number of input bits of the convolutional code..."

A workaround in porting Matlab Communications Toolbox examples to komm is to append a traceback_length array of zeros to the input message, and discard the first traceback_array length (zeros) from the decoded message. This effective latency is not too dissimilar to convolutional code use in practice.

Example code excerpt which uses tx_bin as a 8*Npixels array of binary:

code = komm.ConvolutionalCode(feedforward_polynomials=[[0o117, 0o155]])
len = code.overall_constraint_length
conv_encoder = komm.ConvolutionalStreamEncoder(code)
conv_decoder = komm.ConvolutionalStreamDecoder(code, traceback_length=5*len)

tx_enc = numpy.uint8(conv_encoder(numpy.append(tx_bin,numpy.zeros(conv_decoder._traceback_length))))
rx_enc = tx_enc
rx_bin = numpy.uint8(conv_decoder(rx_enc))[-8*Npixels:]

**Comment by rwnobrega** [comment]
Thanks a lot for your feedback!

But in fact this exact same functionality is implemented by MATLAB when `'TerminationMethod'` is set to `'Continous'`. See:
```matlab
>> % MATLAB R2015a
>> convolutional_decoder = comm.ViterbiDecoder( ...
   'TrellisStructure', poly2trellis(3, [7 5]), ...
   'TracebackDepth', 10, ...
   'TerminationMethod', 'Continuous', ...
   'InputFormat', 'Hard');
>> convolutional_decoder.step([1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1]')'
ans =
     0     0     0     0     0     0     0     0     0     0
>> convolutional_decoder.step(zeros(2*10, 1))'
ans =
     1     0     1     1     1     0     1     1     0     0
```
This matches exactly the example in [komm.ConvolutionalStreamDecoder](https://komm.readthedocs.io/en/latest/komm.ConvolutionalStreamDecoder/) documentation.

Alternatively, you may also want to take a look at [komm.TerminatedConvolutionalCode](https://komm.readthedocs.io/en/latest/komm.TerminatedConvolutionalCode/), and use `.encode` and `.decode` methods.

**Comment by rwnobrega** [comment]
I'm glad to hear that. Reports, patches and suggestions are always welcome. I'm closing this issue.
