### ISSUE TITLE
TypeError in komm

### ISSUE THREAD

**Issue by dchutchings** [rwnobrega/komm#20]
Revisited komm projects for my class next semester and found errors in modulation and demodulation examples using PSK and QAM. 
After updating to latest version of komm, I'm left with the following problem.

I can supply example codes if needed.

Thanks,
Prof. David Hutchings

runfile('C:/Users/dch2y/OneDrive - University of Glasgow/DigiComms4/parity_psk.py', wdir='C:/Users/dch2y/OneDrive - University of Glasgow/DigiComms4')
Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\dch2y\onedrive - university of glasgow\digicomms4\parity_psk.py:12
    import komm

  File C:\ProgramData\Anaconda3\lib\site-packages\komm\__init__.py:3
    from ._algebra import *

  File C:\ProgramData\Anaconda3\lib\site-packages\komm\_algebra\__init__.py:2
    from .BinaryPolynomialFraction import BinaryPolynomialFraction

  File C:\ProgramData\Anaconda3\lib\site-packages\komm\_algebra\BinaryPolynomialFraction.py:5
    class BinaryPolynomialFraction:

  File C:\ProgramData\Anaconda3\lib\site-packages\komm\_algebra\BinaryPolynomialFraction.py:10 in BinaryPolynomialFraction
    def __init__(self, numerator: int | BinaryPolynomial, denominator: int | BinaryPolynomial = 0b1):

TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by rwnobrega** [comment]
Dear @dchutchings,

Can you please tell me which version of Python are you using? Komm now requires Python 3.10 or above. If it is impossible for you to update, I might consider going back to a lower Python version.

**Comment by rwnobrega** [comment]
Closing after https://github.com/rwnobrega/komm/issues/21#issue-2154258370.
