### ISSUE TITLE
RRC frequency_response missing

### ISSUE THREAD

**Issue by mbe9a** [rwnobrega/komm#5]
Love the code, great job! Did you mean to leave the frequency response function missing for RRC pulses? I guess you could just take the sqrt() of the RC frequency response, but it would be nice to be able to call 'pulse.frequency_response' for RRC pulses.

**Comment by mbe9a** [comment]
Also if I wanted to incorporate oversampling into the filter design, how would I do that?

**Comment by rwnobrega** [comment]
Thanks for the feedback! This is indeed a bug. I'm working on it.

**Comment by rwnobrega** [comment]
I just saw you fixed this on 188b094ef20f554b339c6eed42cf440717f23fbc. So I merged into master. Thank you!

**Comment by mbe9a** [comment]
No problem my man!

I think I figured out what you are doing to design the pulses too. I like it!

The 't' array you provide the pulse function defines everything -- the spacing between time points does actually. The way I incorporated 4X oversampling was making the spacing between points in 't' 0.25. Essentially making 4 points for every '1' unit of time/samples. This is how you intended it yes? It took me a while to figure that out because I've only every used matlab filter design before.

**Comment by rwnobrega** [comment]
> Also if I wanted to incorporate oversampling into the filter design, how would I do that?

Oversampling can be accomplished with `komm.TransmitFilter`. For example:

```python
In [1]: import komm                                                                                                                                                                           

In [2]: pulse = komm.RectangularPulse()                                                                                                                                                       

In [3]: tx_filter = komm.TransmitFilter(pulse=pulse, samples_per_symbol=4)                                                                                                                    

In [4]: tx_filter([1, -1, 0.5])                                                                                                                                                               
Out[4]: array([ 1. ,  1. ,  1. ,  1. , -1. , -1. , -1. , -1. ,  0.5,  0.5,  0.5,  0.5])

In [5]: tx_filter([1])                                                                                                                                                                      
Out[5]: array([1., 1., 1., 1.])
```

The example above uses `komm.RectangularPulse`, but should work with other pulses.

**Comment by mbe9a** [comment]
Oh very cool. I will use that from now on.

**Comment by rwnobrega** [comment]
By the way, maybe `length_in_symbols` should be a property of `TransmitFilter` instead of `SincPulse`, `RaisedCosinePulse`, `RootRaisedCosinePulse`, and `GaussianPulse`. Opinions are welcome.
