### ISSUE TITLE
Cannot install from requirements.txt

### ISSUE THREAD

**Issue by tyculus** [rwnobrega/komm#7]
Hey there! To share my komm project I used `pip freeze > requirements.txt` to document the required packages for my software. But I cannot do `pip install -r requirements.txt` in a separate virtual environment, it fails with the following error:

> __Collecting komm==0.7.0__                                                 
>   Using cached komm-0.7.0.tar.gz (48 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /home/..../venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h00a48ef/komm/setup.py'"'"'; \__file\__='"'"'/tmp/pip-install-h00a48ef/komm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(\__file\__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, \__file\__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_mqzfwp5                                                                                                                                                              
>          cwd: /tmp/pip-install-h00a48ef/komm/                                                                                                                                                                  
>     Complete output (9 lines):                                                                                                                                                                                 
>     Traceback (most recent call last):                                                                                                                                                                         
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-h00a48ef/komm/setup.py", line 2, in <module>
>         from komm import \__version\__
>       File "/tmp/pip-install-h00a48ef/komm/komm/\__init\__.py", line 3, in <module>
>         from ._algebra import *
>       File "/tmp/pip-install-h00a48ef/komm/komm/_algebra.py", line 3, in <module>
>         import numpy as np
>     __ModuleNotFoundError: No module named 'numpy'__
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

It seems that komm depends on numpy upon installation and as a result one first has to install numpy and then komm afterwards with two separate pip commands. Therefore it is be impossible to use a single `pip install -r requirements.txt` to install all dependencies. This is not the case for other libraries that depend on numpy. Is it necessary to depend on numpy during installation or could this be fixed?
Thanks!

**Comment by rwnobrega** [comment]
Hello.  Thanks for pointing that out!  The problem was that `komm` was being imported by `setup.py`.  Fixed with e73a0bdc314178714e2f7f8152a7e0416f2d8889 and released `v0.7.1` to PyPI.  Could you please test if it is working now?

**Comment by tyculus** [comment]
Yes it works perfectly. Thank you!
